apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crate-demo-ingress
spec:
  rules:
    - host: crate-demo.example.com
      http:
        paths:
          - path: /crate-demo
            backend:
              serviceName: crate-demo-service
              servicePort: 443
