apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crate-demo-ingress
  annotations:
    cert-manager.io/cluster-issuer: test-ca-cluster-issuer
spec:
  rules:
  - host: crate-demo.example.com
    http:
      paths:
        - path: /crate-demo
          backend:
            serviceName: crate-demo-service
            servicePort: 443
  tls:
  - hosts:
    - crate-demo.example.com
    secretName: myingress-cert