apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: apps/demo
    repoURL: https://github.com/shyukri/demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
